--- 
document: 
  description: "La normativa cosiddetta FOIA (Freedom of Information Act), introdotta con decreto legislativo n. 97 del 2016, è parte integrante del processo di riforma della pubblica amministrazione, definito dalla legge 7 agosto 2015, n. 124 (c.d. legge Madia)."
  name: "Accesso civico generalizzato. Norme sull'attuazione, circolare n. 2 del 2017"
  tags: 
    - norme
